Algoritmo "soma entre eles dois números inteiros."
//1. Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório entre eles
Var
    numero1,numero2,soma: inteiro


Inicio
      Escreva("Digite um numero:")
      leia(numero1)
      Escreva("Digite outro numero:")
      leia(numero2)
      soma := numero1 + numero2
      Escreva("A soma entre ", numero1, " e ", numero2, " é igual a ", soma, ".")

Fimalgoritmo


